### PR TITLE
Add guide on how to purchase something

### PR DESCRIPTION
**Pull request by kellylee-gds**

### CODE REVIEW

**Review by christopherthomasdesign — COMMENTED** [review]
Thanks @kellylee-gds! The content here seems to focus mostly on purchasing new tools or software. The name of the page suggests a broader scope to me, for example, does it include things like buying stickers for an event? Should it include anything on when it's appropriate to self-expense something?

**Comment by kellylee-gds** [comment]
@christopherthomasdesign yes I think it should include those things too.

In the case of self-expensing, we should probably just link to the intranet guidance. Costs for things like stickers is included in our yearly budget but it's paid for usually by the individual then expensed. I'll add some content about that 👍🏻

**Comment by kellylee-gds** [comment]
@christopherthomasdesign I've tweaked the content to be less about tooling specifically, and added info about smaller purchases. Let me know what you think

**Review by christopherthomasdesign — APPROVED** [review]
Really good. Thanks for adding that extra stuff in! Reads clearly to me.

**Pull request merged**
